### ISSUE TITLE
NewClient should not have jsonbox.io as url

### ISSUE THREAD

**Issue by iambenkay** [peteretelej/jsonbox#1]
since it was built for jsonbox then it should not have to request the input as in
```go
cl,err := jsonbox.NewClient("https://jsonbox.io/")
```
Instead it should be
```go
cl, err := jsonbox.NewClient("<BOX_ID>")
```
then
```go
cl.Create(val)
cl.Delete(val)
```

**Comment by peteretelej** [comment]
based on the jsonbox docs https://github.com/vasanthv/jsonbox#create `BOXID` should refer to a "box" inside the jsonbox instance  eg 
`https://jsonbox.io/demobox_6d9e326c183fde7b` -> `jsonbox.io/${BOX_ID}` 

Meaning for generic placeholder it should be something like `jsonbox.NewClient("<JSONBOX_URL>")` instead.

The `BOX_ID` should be here:
```
out, err := cl.Create("<BOX_ID>",val)
```

**Comment by peteretelej** [comment]
> since it was built for jsonbox then it should not have to request the input as in

Not built for `jsonbox.io` alone. Meaning it will work for any `jsonbox` server, eg if you use https://github.com/vasanthv/jsonbox to run your own version at `https://example.com`, you should be able to use:

```
cl,err := jsonbox.NewClient("https://example.com/")
```

**Comment by iambenkay** [comment]
Okay, thanks.
